// S6: Global Reference seeding — Countries, Currencies, Industries (SSIC 2020)
// AC: Country.findMany() returns 249 entries; SG has uenPattern set.

import type { PrismaClient } from '@prisma/client';

// ── Countries (all ISO 3166-1 alpha-2, 249 entries) ──────────────────────────

interface CountrySeed {
  code: string;
  name: string;
  uenPattern?: string;
}

export const COUNTRIES: CountrySeed[] = [
  { code: 'AF', name: 'Afghanistan' },
  { code: 'AX', name: 'Åland Islands' },
  { code: 'AL', name: 'Albania' },
  { code: 'DZ', name: 'Algeria' },
  { code: 'AS', name: 'American Samoa' },
  { code: 'AD', name: 'Andorra' },
  { code: 'AO', name: 'Angola' },
  { code: 'AI', name: 'Anguilla' },
  { code: 'AQ', name: 'Antarctica' },
  { code: 'AG', name: 'Antigua and Barbuda' },
  { code: 'AR', name: 'Argentina' },
  { code: 'AM', name: 'Armenia' },
  { code: 'AW', name: 'Aruba' },
  { code: 'AU', name: 'Australia' },
  { code: 'AT', name: 'Austria' },
  { code: 'AZ', name: 'Azerbaijan' },
  { code: 'BS', name: 'Bahamas' },
  { code: 'BH', name: 'Bahrain' },
  { code: 'BD', name: 'Bangladesh' },
  { code: 'BB', name: 'Barbados' },
  { code: 'BY', name: 'Belarus' },
  { code: 'BE', name: 'Belgium' },
  { code: 'BZ', name: 'Belize' },
  { code: 'BJ', name: 'Benin' },
  { code: 'BM', name: 'Bermuda' },
  { code: 'BT', name: 'Bhutan' },
  { code: 'BO', name: 'Bolivia (Plurinational State of)' },
  { code: 'BQ', name: 'Bonaire, Sint Eustatius and Saba' },
  { code: 'BA', name: 'Bosnia and Herzegovina' },
  { code: 'BW', name: 'Botswana' },
  { code: 'BV', name: 'Bouvet Island' },
  { code: 'BR', name: 'Brazil' },
  { code: 'IO', name: 'British Indian Ocean Territory' },
  { code: 'BN', name: 'Brunei Darussalam' },
  { code: 'BG', name: 'Bulgaria' },
  { code: 'BF', name: 'Burkina Faso' },
  { code: 'BI', name: 'Burundi' },
  { code: 'CV', name: 'Cabo Verde' },
  { code: 'KH', name: 'Cambodia' },
  { code: 'CM', name: 'Cameroon' },
  { code: 'CA', name: 'Canada' },
  { code: 'KY', name: 'Cayman Islands' },
  { code: 'CF', name: 'Central African Republic' },
  { code: 'TD', name: 'Chad' },
  { code: 'CL', name: 'Chile' },
  { code: 'CN', name: 'China' },
  { code: 'CX', name: 'Christmas Island' },
  { code: 'CC', name: 'Cocos (Keeling) Islands' },
  { code: 'CO', name: 'Colombia' },
  { code: 'KM', name: 'Comoros' },
  { code: 'CG', name: 'Congo' },
  { code: 'CD', name: 'Congo, Democratic Republic of the' },
  { code: 'CK', name: 'Cook Islands' },
  { code: 'CR', name: 'Costa Rica' },
  { code: 'CI', name: "Côte d'Ivoire" },
  { code: 'HR', name: 'Croatia' },
  { code: 'CU', name: 'Cuba' },
  { code: 'CW', name: 'Curaçao' },
  { code: 'CY', name: 'Cyprus' },
  { code: 'CZ', name: 'Czechia' },
  { code: 'DK', name: 'Denmark' },
  { code: 'DJ', name: 'Djibouti' },
  { code: 'DM', name: 'Dominica' },
  { code: 'DO', name: 'Dominican Republic' },
  { code: 'EC', name: 'Ecuador' },
  { code: 'EG', name: 'Egypt' },
  { code: 'SV', name: 'El Salvador' },
  { code: 'GQ', name: 'Equatorial Guinea' },
  { code: 'ER', name: 'Eritrea' },
  { code: 'EE', name: 'Estonia' },
  { code: 'SZ', name: 'Eswatini' },
  { code: 'ET', name: 'Ethiopia' },
  { code: 'FK', name: 'Falkland Islands (Malvinas)' },
  { code: 'FO', name: 'Faroe Islands' },
  { code: 'FJ', name: 'Fiji' },
  { code: 'FI', name: 'Finland' },
  { code: 'FR', name: 'France' },
  { code: 'GF', name: 'French Guiana' },
  { code: 'PF', name: 'French Polynesia' },
  { code: 'TF', name: 'French Southern Territories' },
  { code: 'GA', name: 'Gabon' },
  { code: 'GM', name: 'Gambia' },
  { code: 'GE', name: 'Georgia' },
  { code: 'DE', name: 'Germany' },
  { code: 'GH', name: 'Ghana' },
  { code: 'GI', name: 'Gibraltar' },
  { code: 'GR', name: 'Greece' },
  { code: 'GL', name: 'Greenland' },
  { code: 'GD', name: 'Grenada' },
  { code: 'GP', name: 'Guadeloupe' },
  { code: 'GU', name: 'Guam' },
  { code: 'GT', name: 'Guatemala' },
  { code: 'GG', name: 'Guernsey' },
  { code: 'GN', name: 'Guinea' },
  { code: 'GW', name: 'Guinea-Bissau' },
  { code: 'GY', name: 'Guyana' },
  { code: 'HT', name: 'Haiti' },
  { code: 'HM', name: 'Heard Island and McDonald Islands' },
  { code: 'VA', name: 'Holy See' },
  { code: 'HN', name: 'Honduras' },
  { code: 'HK', name: 'Hong Kong' },
  { code: 'HU', name: 'Hungary' },
  { code: 'IS', name: 'Iceland' },
  { code: 'IN', name: 'India' },
  { code: 'ID', name: 'Indonesia' },
  { code: 'IR', name: 'Iran (Islamic Republic of)' },
  { code: 'IQ', name: 'Iraq' },
  { code: 'IE', name: 'Ireland' },
  { code: 'IM', name: 'Isle of Man' },
  { code: 'IL', name: 'Israel' },
  { code: 'IT', name: 'Italy' },
  { code: 'JM', name: 'Jamaica' },
  { code: 'JP', name: 'Japan' },
  { code: 'JE', name: 'Jersey' },
  { code: 'JO', name: 'Jordan' },
  { code: 'KZ', name: 'Kazakhstan' },
  { code: 'KE', name: 'Kenya' },
  { code: 'KI', name: 'Kiribati' },
  { code: 'KP', name: "Korea (Democratic People's Republic of)" },
  { code: 'KR', name: 'Korea, Republic of' },
  { code: 'KW', name: 'Kuwait' },
  { code: 'KG', name: 'Kyrgyzstan' },
  { code: 'LA', name: "Lao People's Democratic Republic" },
  { code: 'LV', name: 'Latvia' },
  { code: 'LB', name: 'Lebanon' },
  { code: 'LS', name: 'Lesotho' },
  { code: 'LR', name: 'Liberia' },
  { code: 'LY', name: 'Libya' },
  { code: 'LI', name: 'Liechtenstein' },
  { code: 'LT', name: 'Lithuania' },
  { code: 'LU', name: 'Luxembourg' },
  { code: 'MO', name: 'Macao' },
  { code: 'MG', name: 'Madagascar' },
  { code: 'MW', name: 'Malawi' },
  { code: 'MY', name: 'Malaysia', uenPattern: '^[0-9]{6,12}-[A-Z0-9]$' },
  { code: 'MV', name: 'Maldives' },
  { code: 'ML', name: 'Mali' },
  { code: 'MT', name: 'Malta' },
  { code: 'MH', name: 'Marshall Islands' },
  { code: 'MQ', name: 'Martinique' },
  { code: 'MR', name: 'Mauritania' },
  { code: 'MU', name: 'Mauritius' },
  { code: 'YT', name: 'Mayotte' },
  { code: 'MX', name: 'Mexico' },
  { code: 'FM', name: 'Micronesia (Federated States of)' },
  { code: 'MD', name: 'Moldova, Republic of' },
  { code: 'MC', name: 'Monaco' },
  { code: 'MN', name: 'Mongolia' },
  { code: 'ME', name: 'Montenegro' },
  { code: 'MS', name: 'Montserrat' },
  { code: 'MA', name: 'Morocco' },
  { code: 'MZ', name: 'Mozambique' },
  { code: 'MM', name: 'Myanmar' },
  { code: 'NA', name: 'Namibia' },
  { code: 'NR', name: 'Nauru' },
  { code: 'NP', name: 'Nepal' },
  { code: 'NL', name: 'Netherlands' },
  { code: 'NC', name: 'New Caledonia' },
  { code: 'NZ', name: 'New Zealand' },
  { code: 'NI', name: 'Nicaragua' },
  { code: 'NE', name: 'Niger' },
  { code: 'NG', name: 'Nigeria' },
  { code: 'NU', name: 'Niue' },
  { code: 'NF', name: 'Norfolk Island' },
  { code: 'MK', name: 'North Macedonia' },
  { code: 'MP', name: 'Northern Mariana Islands' },
  { code: 'NO', name: 'Norway' },
  { code: 'OM', name: 'Oman' },
  { code: 'PK', name: 'Pakistan' },
  { code: 'PW', name: 'Palau' },
  { code: 'PS', name: 'Palestine, State of' },
  { code: 'PA', name: 'Panama' },
  { code: 'PG', name: 'Papua New Guinea' },
  { code: 'PY', name: 'Paraguay' },
  { code: 'PE', name: 'Peru' },
  { code: 'PH', name: 'Philippines' },
  { code: 'PN', name: 'Pitcairn' },
  { code: 'PL', name: 'Poland' },
  { code: 'PT', name: 'Portugal' },
  { code: 'PR', name: 'Puerto Rico' },
  { code: 'QA', name: 'Qatar' },
  { code: 'RE', name: 'Réunion' },
  { code: 'RO', name: 'Romania' },
  { code: 'RU', name: 'Russian Federation' },
  { code: 'RW', name: 'Rwanda' },
  { code: 'BL', name: 'Saint Barthélemy' },
  { code: 'SH', name: 'Saint Helena, Ascension and Tristan da Cunha' },
  { code: 'KN', name: 'Saint Kitts and Nevis' },
  { code: 'LC', name: 'Saint Lucia' },
  { code: 'MF', name: 'Saint Martin (French part)' },
  { code: 'PM', name: 'Saint Pierre and Miquelon' },
  { code: 'VC', name: 'Saint Vincent and the Grenadines' },
  { code: 'WS', name: 'Samoa' },
  { code: 'SM', name: 'San Marino' },
  { code: 'ST', name: 'Sao Tome and Principe' },
  { code: 'SA', name: 'Saudi Arabia' },
  { code: 'SN', name: 'Senegal' },
  { code: 'RS', name: 'Serbia' },
  { code: 'SC', name: 'Seychelles' },
  { code: 'SL', name: 'Sierra Leone' },
  {
    code: 'SG',
    name: 'Singapore',
    uenPattern: '^[0-9]{8,10}[A-Z]$', // ACRA UEN
  },
  { code: 'SX', name: 'Sint Maarten (Dutch part)' },
  { code: 'SK', name: 'Slovakia' },
  { code: 'SI', name: 'Slovenia' },
  { code: 'SB', name: 'Solomon Islands' },
  { code: 'SO', name: 'Somalia' },
  { code: 'ZA', name: 'South Africa' },
  { code: 'GS', name: 'South Georgia and the South Sandwich Islands' },
  { code: 'SS', name: 'South Sudan' },
  { code: 'ES', name: 'Spain' },
  { code: 'LK', name: 'Sri Lanka' },
  { code: 'SD', name: 'Sudan' },
  { code: 'SR', name: 'Suriname' },
  { code: 'SJ', name: 'Svalbard and Jan Mayen' },
  { code: 'SE', name: 'Sweden' },
  { code: 'CH', name: 'Switzerland' },
  { code: 'SY', name: 'Syrian Arab Republic' },
  { code: 'TW', name: 'Taiwan, Province of China' },
  { code: 'TJ', name: 'Tajikistan' },
  { code: 'TZ', name: 'Tanzania, United Republic of' },
  { code: 'TH', name: 'Thailand' },
  { code: 'TL', name: 'Timor-Leste' },
  { code: 'TG', name: 'Togo' },
  { code: 'TK', name: 'Tokelau' },
  { code: 'TO', name: 'Tonga' },
  { code: 'TT', name: 'Trinidad and Tobago' },
  { code: 'TN', name: 'Tunisia' },
  { code: 'TR', name: 'Türkiye' },
  { code: 'TM', name: 'Turkmenistan' },
  { code: 'TC', name: 'Turks and Caicos Islands' },
  { code: 'TV', name: 'Tuvalu' },
  { code: 'UG', name: 'Uganda' },
  { code: 'UA', name: 'Ukraine' },
  { code: 'AE', name: 'United Arab Emirates' },
  { code: 'GB', name: 'United Kingdom of Great Britain and Northern Ireland' },
  { code: 'UM', name: 'United States Minor Outlying Islands' },
  { code: 'US', name: 'United States of America' },
  { code: 'UY', name: 'Uruguay' },
  { code: 'UZ', name: 'Uzbekistan' },
  { code: 'VU', name: 'Vanuatu' },
  { code: 'VE', name: 'Venezuela (Bolivarian Republic of)' },
  { code: 'VN', name: 'Viet Nam' },
  { code: 'VG', name: 'Virgin Islands (British)' },
  { code: 'VI', name: 'Virgin Islands (U.S.)' },
  { code: 'WF', name: 'Wallis and Futuna' },
  { code: 'EH', name: 'Western Sahara' },
  { code: 'YE', name: 'Yemen' },
  { code: 'ZM', name: 'Zambia' },
  { code: 'ZW', name: 'Zimbabwe' },
];

// ── Currencies ────────────────────────────────────────────────────────────────

interface CurrencySeed {
  code: string;
  name: string;
  decimals: number;
}

export const CURRENCIES: CurrencySeed[] = [
  { code: 'SGD', name: 'Singapore Dollar', decimals: 2 },
  { code: 'USD', name: 'United States Dollar', decimals: 2 },
  { code: 'MYR', name: 'Malaysian Ringgit', decimals: 2 },
  { code: 'EUR', name: 'Euro', decimals: 2 },
  { code: 'GBP', name: 'Pound Sterling', decimals: 2 },
  { code: 'JPY', name: 'Japanese Yen', decimals: 0 },
  { code: 'CNY', name: 'Yuan Renminbi', decimals: 2 },
  { code: 'HKD', name: 'Hong Kong Dollar', decimals: 2 },
  { code: 'AUD', name: 'Australian Dollar', decimals: 2 },
];

// ── Industries — SG SSIC 2020 ─────────────────────────────────────────────────
// Source: Singapore Standard Industrial Classification 2020 (SingStat)
// Full list: https://www.singstat.gov.sg/standards/standards-and-classifications/ssic
//
// Structure: 5-digit subclass codes (most granular level used in practice).
// parentCode = 4-digit class, which in turn has 3-digit group parent, etc.
// We seed at 5-digit subclass level; parentCode left null at this level
// to keep the table flat — add hierarchy if needed via a future migration.

interface IndustrySeed {
  code: string;
  name: string;
  parentCode?: string;
}

export const INDUSTRIES: IndustrySeed[] = [
  // ── Section A: Agriculture, Forestry and Fishing ──────────────────────────
  { code: '01110', name: 'Growing of cereals (except rice), leguminous crops and oil seeds' },
  { code: '01120', name: 'Growing of rice' },
  { code: '01130', name: 'Growing of vegetables and melons, roots and tubers' },
  { code: '01140', name: 'Growing of sugar cane' },
  { code: '01150', name: 'Growing of tobacco' },
  { code: '01160', name: 'Growing of fibre crops' },
  { code: '01190', name: 'Growing of other non-perennial crops' },
  { code: '01210', name: 'Growing of grapes' },
  { code: '01220', name: 'Growing of tropical and subtropical fruits' },
  { code: '01230', name: 'Growing of citrus fruits' },
  { code: '01240', name: 'Growing of pome and stone fruits' },
  { code: '01250', name: 'Growing of other tree and bush fruits and nuts' },
  { code: '01260', name: 'Growing of oleaginous fruits' },
  { code: '01270', name: 'Growing of beverage crops' },
  { code: '01280', name: 'Growing of spices, aromatic, drug and pharmaceutical crops' },
  { code: '01290', name: 'Growing of other perennial crops' },
  { code: '01300', name: 'Plant propagation' },
  { code: '01410', name: 'Raising of dairy cattle' },
  { code: '01420', name: 'Raising of other cattle and buffaloes' },
  { code: '01430', name: 'Raising of horses and other equines' },
  { code: '01440', name: 'Raising of camels and camelids' },
  { code: '01450', name: 'Raising of sheep and goats' },
  { code: '01460', name: 'Raising of swine/pigs' },
  { code: '01470', name: 'Raising of poultry' },
  { code: '01490', name: 'Raising of other animals' },
  { code: '01500', name: 'Mixed farming' },
  { code: '01610', name: 'Support activities for crop production' },
  { code: '01621', name: 'Farm animal boarding and care' },
  { code: '01629', name: 'Support activities for animal production (other)' },
  { code: '01700', name: 'Hunting, trapping and related service activities' },
  { code: '02100', name: 'Silviculture and other forestry activities' },
  { code: '02200', name: 'Logging' },
  { code: '02300', name: 'Gathering of non-wood forest products' },
  { code: '02400', name: 'Support services to forestry' },
  { code: '03110', name: 'Marine fishing' },
  { code: '03120', name: 'Freshwater fishing' },
  { code: '03210', name: 'Marine aquaculture' },
  { code: '03220', name: 'Freshwater aquaculture' },

  // ── Section B: Mining and Quarrying ───────────────────────────────────────
  { code: '06100', name: 'Extraction of crude petroleum' },
  { code: '06200', name: 'Extraction of natural gas' },
  {
    code: '08110',
    name: 'Quarrying of ornamental and building stone, limestone, gypsum, chalk and slate',
  },
  { code: '08120', name: 'Operation of gravel and sand pits; mining of clays and kaolin' },
  { code: '09100', name: 'Support activities for petroleum and natural gas extraction' },

  // ── Section C: Manufacturing ───────────────────────────────────────────────
  { code: '10101', name: 'Processing and preserving of meat' },
  { code: '10102', name: 'Production of meat products' },
  { code: '10201', name: 'Processing of fish and fish products' },
  { code: '10310', name: 'Processing and preserving of potatoes' },
  { code: '10320', name: 'Manufacture of fruit and vegetable juice' },
  { code: '10390', name: 'Other processing and preserving of fruit and vegetables' },
  { code: '10410', name: 'Manufacture of oils and fats' },
  { code: '10420', name: 'Manufacture of margarine and similar edible fats' },
  { code: '10500', name: 'Manufacture of dairy products' },
  { code: '10611', name: 'Grain milling' },
  { code: '10612', name: 'Rice milling' },
  { code: '10620', name: 'Manufacture of starches and starch products' },
  { code: '10710', name: 'Manufacture of bread; manufacture of fresh pastry goods and cakes' },
  {
    code: '10720',
    name: 'Manufacture of rusks and biscuits; manufacture of preserved pastry goods and cakes',
  },
  {
    code: '10730',
    name: 'Manufacture of macaroni, noodles, couscous and similar farinaceous products',
  },
  { code: '10740', name: 'Manufacture of ready-to-eat food' },
  { code: '10800', name: 'Manufacture of other food products' },
  { code: '10900', name: 'Manufacture of prepared animal feeds' },
  { code: '11010', name: 'Distilling, rectifying and blending of spirits' },
  { code: '11020', name: 'Manufacture of wines' },
  { code: '11030', name: 'Manufacture of malt liquors and malt' },
  {
    code: '11040',
    name: 'Manufacture of soft drinks; production of mineral waters and other bottled waters',
  },
  { code: '12000', name: 'Manufacture of tobacco products' },
  { code: '13100', name: 'Preparation and spinning of textile fibres' },
  { code: '13200', name: 'Weaving of textiles' },
  { code: '13300', name: 'Finishing of textiles' },
  { code: '13910', name: 'Manufacture of knitted and crocheted fabrics' },
  { code: '13920', name: 'Manufacture of made-up textile articles, except apparel' },
  { code: '13930', name: 'Manufacture of carpets and rugs' },
  { code: '14100', name: 'Manufacture of wearing apparel, except fur apparel' },
  { code: '14200', name: 'Manufacture of articles of fur' },
  { code: '14300', name: 'Manufacture of knitted and crocheted apparel' },
  { code: '15110', name: 'Tanning and dressing of leather; dressing and dyeing of fur' },
  { code: '15120', name: 'Manufacture of luggage, handbags and the like, saddlery and harness' },
  { code: '15200', name: 'Manufacture of footwear' },
  { code: '16100', name: 'Sawmilling and planing of wood' },
  { code: '16210', name: 'Manufacture of veneer sheets and wood-based panels' },
  { code: '16220', name: 'Manufacture of assembled parquet floors' },
  { code: '16230', name: 'Manufacture of other builders carpentry and joinery' },
  { code: '16240', name: 'Manufacture of wooden containers' },
  {
    code: '16290',
    name: 'Manufacture of other products of wood; manufacture of articles of cork, straw and plaiting materials',
  },
  { code: '17110', name: 'Manufacture of pulp' },
  { code: '17120', name: 'Manufacture of paper and paperboard' },
  {
    code: '17210',
    name: 'Manufacture of corrugated paper and paperboard and of containers of paper and paperboard',
  },
  { code: '17220', name: 'Manufacture of household and sanitary goods and of toilet requisites' },
  { code: '17230', name: 'Manufacture of paper stationery' },
  { code: '17290', name: 'Manufacture of other articles of paper and paperboard' },
  { code: '18110', name: 'Printing' },
  { code: '18120', name: 'Service activities related to printing' },
  { code: '18200', name: 'Reproduction of recorded media' },
  { code: '19100', name: 'Manufacture of coke oven products' },
  { code: '19200', name: 'Manufacture of refined petroleum products' },
  { code: '20110', name: 'Manufacture of industrial gases' },
  { code: '20120', name: 'Manufacture of dyes and pigments' },
  { code: '20130', name: 'Manufacture of other inorganic basic chemicals' },
  { code: '20140', name: 'Manufacture of other organic basic chemicals' },
  { code: '20150', name: 'Manufacture of fertilisers and nitrogen compounds' },
  { code: '20160', name: 'Manufacture of plastics in primary forms' },
  { code: '20170', name: 'Manufacture of synthetic rubber in primary forms' },
  { code: '20200', name: 'Manufacture of pesticides and other agrochemical products' },
  { code: '20301', name: 'Manufacture of paints and varnishes' },
  { code: '20302', name: 'Manufacture of printing ink' },
  {
    code: '20410',
    name: 'Manufacture of soap and detergents, cleaning and polishing preparations',
  },
  { code: '20420', name: 'Manufacture of perfumes and toilet preparations' },
  { code: '20510', name: 'Manufacture of explosives' },
  { code: '20520', name: 'Manufacture of glues' },
  { code: '20530', name: 'Manufacture of essential oils' },
  { code: '20590', name: 'Manufacture of other chemical products n.e.c.' },
  { code: '20600', name: 'Manufacture of man-made fibres' },
  { code: '21000', name: 'Manufacture of pharmaceutical products and pharmaceutical preparations' },
  {
    code: '22110',
    name: 'Manufacture of rubber tyres and tubes; retreading and rebuilding of rubber tyres',
  },
  { code: '22190', name: 'Manufacture of other rubber products' },
  { code: '22210', name: 'Manufacture of plastic plates, sheets, tubes and profiles' },
  { code: '22220', name: 'Manufacture of plastic packing goods' },
  { code: '22230', name: 'Manufacture of builders ware of plastic' },
  { code: '22290', name: 'Manufacture of other plastic products' },
  { code: '23110', name: 'Manufacture of flat glass' },
  { code: '23120', name: 'Shaping and processing of flat glass' },
  { code: '23130', name: 'Manufacture of hollow glass' },
  { code: '23140', name: 'Manufacture of glass fibres' },
  {
    code: '23190',
    name: 'Manufacture and processing of other glass, including technical glassware',
  },
  { code: '23200', name: 'Manufacture of refractory products' },
  { code: '23310', name: 'Manufacture of ceramic tiles and flags' },
  { code: '23320', name: 'Manufacture of bricks, tiles and construction products, in baked clay' },
  { code: '23410', name: 'Manufacture of ceramic household and ornamental articles' },
  { code: '23420', name: 'Manufacture of ceramic sanitary fixtures' },
  { code: '23430', name: 'Manufacture of ceramic insulators and insulating fittings' },
  { code: '23440', name: 'Manufacture of other technical ceramic products' },
  { code: '23490', name: 'Manufacture of other ceramic products' },
  { code: '23500', name: 'Manufacture of cement, lime and plaster' },
  { code: '23610', name: 'Manufacture of concrete products for construction purposes' },
  { code: '23690', name: 'Manufacture of other articles of concrete, plaster and cement' },
  { code: '23700', name: 'Cutting, shaping and finishing of stone' },
  {
    code: '23900',
    name: 'Manufacture of abrasive products and non-metallic mineral products n.e.c.',
  },
  { code: '24100', name: 'Manufacture of basic iron and steel' },
  {
    code: '24200',
    name: 'Manufacture of tubes, pipes, hollow profiles and related fittings, of steel',
  },
  { code: '24310', name: 'Cold drawing of bars' },
  { code: '24320', name: 'Cold rolling of narrow strip' },
  { code: '24330', name: 'Cold forming or folding' },
  { code: '24340', name: 'Cold drawing of wire' },
  { code: '24410', name: 'Precious metals production' },
  { code: '24420', name: 'Aluminium production' },
  { code: '24430', name: 'Lead, zinc and tin production' },
  { code: '24440', name: 'Copper production' },
  { code: '24450', name: 'Other non-ferrous metal production' },
  { code: '24460', name: 'Processing of nuclear fuel' },
  { code: '24510', name: 'Casting of iron' },
  { code: '24520', name: 'Casting of steel' },
  { code: '24530', name: 'Casting of light metals' },
  { code: '24540', name: 'Casting of other non-ferrous metals' },
  { code: '25110', name: 'Manufacture of metal structures and parts of structures' },
  { code: '25120', name: 'Manufacture of doors and windows of metal' },
  { code: '25210', name: 'Manufacture of central heating radiators and boilers' },
  { code: '25290', name: 'Manufacture of other tanks, reservoirs and containers of metal' },
  {
    code: '25300',
    name: 'Manufacture of steam generators, except central heating hot water boilers',
  },
  { code: '25400', name: 'Manufacture of weapons and ammunition' },
  { code: '25501', name: 'Forging, pressing, stamping and roll-forming of metal' },
  { code: '25502', name: 'Powder metallurgy' },
  { code: '25610', name: 'Treatment and coating of metals' },
  { code: '25620', name: 'Machining' },
  { code: '25710', name: 'Manufacture of cutlery' },
  { code: '25720', name: 'Manufacture of locks and hinges' },
  { code: '25730', name: 'Manufacture of tools' },
  { code: '25910', name: 'Manufacture of steel drums and similar containers' },
  { code: '25920', name: 'Manufacture of light metal packaging' },
  { code: '25930', name: 'Manufacture of wire products, chain and springs' },
  { code: '25940', name: 'Manufacture of fasteners and screw machine products' },
  { code: '25990', name: 'Manufacture of other fabricated metal products n.e.c.' },
  { code: '26110', name: 'Manufacture of electronic components' },
  { code: '26120', name: 'Manufacture of loaded electronic boards' },
  { code: '26200', name: 'Manufacture of computers and peripheral equipment' },
  { code: '26300', name: 'Manufacture of communication equipment' },
  { code: '26400', name: 'Manufacture of consumer electronics' },
  {
    code: '26511',
    name: 'Manufacture of industrial and commercial machinery and equipment for measuring, testing and navigating',
  },
  { code: '26512', name: 'Manufacture of instruments and appliances for measuring and testing' },
  { code: '26520', name: 'Manufacture of watches and clocks' },
  {
    code: '26600',
    name: 'Manufacture of irradiation, electromedical and electrotherapeutic equipment',
  },
  { code: '26700', name: 'Manufacture of optical instruments and photographic equipment' },
  { code: '26800', name: 'Manufacture of magnetic and optical media' },
  {
    code: '27100',
    name: 'Manufacture of electric motors, generators, transformers and electricity distribution and control apparatus',
  },
  { code: '27200', name: 'Manufacture of batteries and accumulators' },
  { code: '27310', name: 'Manufacture of fibre optic cables' },
  { code: '27320', name: 'Manufacture of other electronic and electric wires and cables' },
  { code: '27330', name: 'Manufacture of wiring devices' },
  { code: '27400', name: 'Manufacture of electric lighting equipment' },
  { code: '27510', name: 'Manufacture of electric domestic appliances' },
  { code: '27520', name: 'Manufacture of non-electric domestic appliances' },
  { code: '27900', name: 'Manufacture of other electrical equipment' },
  {
    code: '28110',
    name: 'Manufacture of engines and turbines, except aircraft, vehicle and cycle engines',
  },
  { code: '28120', name: 'Manufacture of fluid power equipment' },
  { code: '28130', name: 'Manufacture of other pumps and compressors' },
  { code: '28140', name: 'Manufacture of other taps and valves' },
  { code: '28150', name: 'Manufacture of bearings, gears, gearing and driving elements' },
  { code: '28160', name: 'Manufacture of lifting and handling equipment' },
  {
    code: '28170',
    name: 'Manufacture of office machinery and equipment (except computers and peripheral equipment)',
  },
  { code: '28180', name: 'Manufacture of power-driven hand tools' },
  { code: '28190', name: 'Manufacture of other general-purpose machinery' },
  { code: '28210', name: 'Manufacture of agricultural and forestry machinery' },
  { code: '28220', name: 'Manufacture of metal-forming machinery and machine tools' },
  { code: '28230', name: 'Manufacture of machinery for metallurgy' },
  { code: '28240', name: 'Manufacture of machinery for mining, quarrying and construction' },
  { code: '28250', name: 'Manufacture of machinery for food, beverage and tobacco processing' },
  { code: '28260', name: 'Manufacture of machinery for textile, apparel and leather production' },
  { code: '28290', name: 'Manufacture of other special-purpose machinery' },
  { code: '29100', name: 'Manufacture of motor vehicles' },
  {
    code: '29200',
    name: 'Manufacture of bodies (coachwork) for motor vehicles; manufacture of trailers and semi-trailers',
  },
  { code: '29310', name: 'Manufacture of electrical and electronic equipment for motor vehicles' },
  { code: '29320', name: 'Manufacture of other parts and accessories for motor vehicles' },
  { code: '30110', name: 'Building of ships and floating structures' },
  { code: '30120', name: 'Building of pleasure and sporting boats' },
  { code: '30200', name: 'Manufacture of railway locomotives and rolling stock' },
  { code: '30300', name: 'Manufacture of air and spacecraft and related machinery' },
  { code: '30400', name: 'Manufacture of military fighting vehicles' },
  { code: '30910', name: 'Manufacture of motorcycles' },
  { code: '30920', name: 'Manufacture of bicycles and invalid carriages' },
  { code: '30990', name: 'Manufacture of other transport equipment n.e.c.' },
  { code: '31000', name: 'Manufacture of furniture' },
  { code: '32110', name: 'Striking of coins' },
  { code: '32120', name: 'Manufacture of jewellery and related articles' },
  { code: '32130', name: 'Manufacture of imitation jewellery and related articles' },
  { code: '32200', name: 'Manufacture of musical instruments' },
  { code: '32300', name: 'Manufacture of sports goods' },
  { code: '32400', name: 'Manufacture of games and toys' },
  { code: '32500', name: 'Manufacture of medical and dental instruments and supplies' },
  { code: '32910', name: 'Manufacture of brooms and brushes' },
  { code: '32990', name: 'Other manufacturing n.e.c.' },
  { code: '33110', name: 'Repair of fabricated metal products' },
  { code: '33120', name: 'Repair of machinery' },
  { code: '33130', name: 'Repair of electronic and optical equipment' },
  { code: '33140', name: 'Repair of electrical equipment' },
  { code: '33150', name: 'Repair and maintenance of ships and boats' },
  { code: '33160', name: 'Repair and maintenance of aircraft and spacecraft' },
  { code: '33170', name: 'Repair and maintenance of other transport equipment' },
  { code: '33190', name: 'Repair of other equipment' },
  { code: '33200', name: 'Installation of industrial machinery and equipment' },

  // ── Section D: Electricity, Gas, Steam ────────────────────────────────────
  { code: '35100', name: 'Electric power generation, transmission and distribution' },
  { code: '35200', name: 'Manufacture of gas; distribution of gaseous fuels through mains' },
  { code: '35300', name: 'Steam and air conditioning supply' },

  // ── Section E: Water Supply, Waste Management ─────────────────────────────
  { code: '36000', name: 'Water collection, treatment and supply' },
  { code: '37000', name: 'Sewerage' },
  { code: '38110', name: 'Collection of non-hazardous waste' },
  { code: '38120', name: 'Collection of hazardous waste' },
  { code: '38210', name: 'Treatment and disposal of non-hazardous waste' },
  { code: '38220', name: 'Treatment and disposal of hazardous waste' },
  { code: '38300', name: 'Materials recovery' },
  { code: '39000', name: 'Remediation activities and other waste management services' },

  // ── Section F: Construction ────────────────────────────────────────────────
  { code: '41001', name: 'Construction of residential buildings' },
  { code: '41002', name: 'Construction of non-residential buildings' },
  { code: '41003', name: 'Real estate development' },
  { code: '42101', name: 'Construction of roads and streets' },
  { code: '42102', name: 'Construction of expressways, elevated highways and tunnels' },
  { code: '42110', name: 'Construction of roads and motorways' },
  { code: '42120', name: 'Construction of railways and underground railways' },
  { code: '42130', name: 'Construction of bridges and tunnels' },
  { code: '42210', name: 'Construction of utility projects for fluids' },
  {
    code: '42220',
    name: 'Construction of utility projects for electricity and telecommunications',
  },
  { code: '42910', name: 'Construction of water projects' },
  { code: '42990', name: 'Construction of other civil engineering projects n.e.c.' },
  { code: '43110', name: 'Demolition' },
  { code: '43120', name: 'Site preparation' },
  { code: '43130', name: 'Test drilling and boring' },
  { code: '43210', name: 'Electrical installation' },
  { code: '43220', name: 'Plumbing, heat and air-conditioning installation' },
  { code: '43290', name: 'Other construction installation' },
  { code: '43310', name: 'Plastering' },
  { code: '43320', name: 'Joinery installation' },
  { code: '43330', name: 'Floor and wall covering' },
  { code: '43340', name: 'Painting and glazing' },
  { code: '43390', name: 'Other building completion and finishing' },
  { code: '43910', name: 'Roofing activities' },
  { code: '43990', name: 'Other specialised construction activities n.e.c.' },

  // ── Section G: Wholesale and Retail Trade ─────────────────────────────────
  { code: '45100', name: 'Sale of motor vehicles' },
  { code: '45200', name: 'Maintenance and repair of motor vehicles' },
  { code: '45310', name: 'Wholesale trade of motor vehicle parts and accessories' },
  { code: '45320', name: 'Retail trade of motor vehicle parts and accessories' },
  {
    code: '45400',
    name: 'Sale, maintenance and repair of motorcycles and related parts and accessories',
  },
  {
    code: '46100',
    name: 'Agents involved in the sale of agricultural raw materials, live animals, textile raw materials and semi-finished goods',
  },
  { code: '46110', name: 'Wholesale on a fee or contract basis — agricultural raw materials' },
  {
    code: '46120',
    name: 'Wholesale on a fee or contract basis — fuels, ores, metals and chemicals',
  },
  { code: '46130', name: 'Wholesale on a fee or contract basis — timber and building materials' },
  {
    code: '46140',
    name: 'Wholesale on a fee or contract basis — machinery, equipment and supplies',
  },
  { code: '46190', name: 'Wholesale on a fee or contract basis — other products' },
  { code: '46200', name: 'Wholesale of agricultural raw materials and live animals' },
  { code: '46310', name: 'Wholesale of fruit and vegetables' },
  { code: '46320', name: 'Wholesale of meat and meat products' },
  { code: '46330', name: 'Wholesale of dairy products, eggs and edible oils and fats' },
  { code: '46340', name: 'Wholesale of beverages' },
  { code: '46350', name: 'Wholesale of tobacco products' },
  { code: '46360', name: 'Wholesale of sugar and chocolate and sugar confectionery' },
  { code: '46370', name: 'Wholesale of coffee, tea, cocoa and spices' },
  { code: '46380', name: 'Wholesale of other food, including fish, crustaceans and molluscs' },
  { code: '46390', name: 'Non-specialised wholesale of food, beverages and tobacco' },
  { code: '46410', name: 'Wholesale of textiles' },
  { code: '46420', name: 'Wholesale of clothing and footwear' },
  {
    code: '46430',
    name: 'Wholesale of electrical household appliances and electronic and telecommunications equipment and parts',
  },
  { code: '46440', name: 'Wholesale of china and glassware and cleaning materials' },
  { code: '46450', name: 'Wholesale of perfume and cosmetics' },
  { code: '46460', name: 'Wholesale of pharmaceutical goods' },
  { code: '46470', name: 'Wholesale of furniture, carpets and lighting equipment' },
  { code: '46480', name: 'Wholesale of watches and jewellery' },
  { code: '46491', name: 'Wholesale of stationery and school and office supplies' },
  { code: '46499', name: 'Wholesale of other household goods n.e.c.' },
  { code: '46510', name: 'Wholesale of computers, computer peripheral equipment and software' },
  { code: '46520', name: 'Wholesale of electronic and telecommunications equipment and parts' },
  { code: '46610', name: 'Wholesale of agricultural machinery, equipment and supplies' },
  { code: '46620', name: 'Wholesale of machine tools' },
  { code: '46630', name: 'Wholesale of mining, construction and civil engineering machinery' },
  {
    code: '46640',
    name: 'Wholesale of machinery for the textile industry and of sewing and knitting machines',
  },
  { code: '46650', name: 'Wholesale of office furniture' },
  { code: '46660', name: 'Wholesale of other office machinery and equipment' },
  { code: '46690', name: 'Wholesale of other machinery and equipment' },
  { code: '46711', name: 'Wholesale of petroleum and petroleum products' },
  { code: '46712', name: 'Wholesale of petrochemical products' },
  {
    code: '46719',
    name: 'Wholesale of other solid, liquid and gaseous fuels and related products',
  },
  { code: '46720', name: 'Wholesale of metals and metal ores' },
  { code: '46730', name: 'Wholesale of wood, construction materials and sanitary equipment' },
  { code: '46740', name: 'Wholesale of hardware, plumbing and heating equipment and supplies' },
  { code: '46750', name: 'Wholesale of chemical products' },
  { code: '46760', name: 'Wholesale of other intermediate products' },
  { code: '46770', name: 'Wholesale of waste and scrap' },
  { code: '46900', name: 'Non-specialised wholesale trade' },
  { code: '47111', name: 'Supermarkets, hypermarkets and provision shops' },
  { code: '47112', name: 'Convenience stores' },
  { code: '47191', name: 'Department stores' },
  { code: '47199', name: 'Other non-specialised retail stores' },
  { code: '47210', name: 'Retail sale of fruit and vegetables in specialised stores' },
  { code: '47220', name: 'Retail sale of meat and meat products in specialised stores' },
  { code: '47230', name: 'Retail sale of fish, crustaceans and molluscs in specialised stores' },
  {
    code: '47240',
    name: 'Retail sale of bread, cakes, flour confectionery and sugar confectionery in specialised stores',
  },
  { code: '47250', name: 'Retail sale of beverages in specialised stores' },
  { code: '47260', name: 'Retail sale of tobacco products in specialised stores' },
  { code: '47290', name: 'Other retail sale of food in specialised stores' },
  { code: '47300', name: 'Retail sale of automotive fuel in specialised stores' },
  { code: '47411', name: 'Retail sale of computers, peripheral units and software' },
  { code: '47412', name: 'Retail sale of telecommunications equipment' },
  { code: '47420', name: 'Retail sale of audio and video equipment in specialised stores' },
  { code: '47510', name: 'Retail sale of textiles in specialised stores' },
  { code: '47520', name: 'Retail sale of hardware, paints and glass in specialised stores' },
  {
    code: '47530',
    name: 'Retail sale of carpets, rugs, wall and floor coverings in specialised stores',
  },
  { code: '47540', name: 'Retail sale of electrical household appliances in specialised stores' },
  {
    code: '47550',
    name: 'Retail sale of furniture, lighting equipment and other household articles in specialised stores',
  },
  { code: '47590', name: 'Retail sale of other household equipment in specialised stores' },
  { code: '47610', name: 'Retail sale of books in specialised stores' },
  { code: '47620', name: 'Retail sale of newspapers and stationery in specialised stores' },
  { code: '47630', name: 'Retail sale of music and video recordings in specialised stores' },
  {
    code: '47641',
    name: 'Retail sale of sporting goods, fishing gear, camping goods, boats and bicycles',
  },
  { code: '47649', name: 'Retail sale of other sporting equipment n.e.c.' },
  { code: '47650', name: 'Retail sale of games and toys in specialised stores' },
  { code: '47710', name: 'Retail sale of clothing in specialised stores' },
  { code: '47721', name: 'Retail sale of footwear in specialised stores' },
  {
    code: '47722',
    name: 'Retail sale of leather goods and travel accessories in specialised stores',
  },
  { code: '47730', name: 'Dispensing chemist in specialised stores' },
  { code: '47740', name: 'Retail sale of medical and orthopaedic goods in specialised stores' },
  { code: '47750', name: 'Retail sale of cosmetic and toilet articles in specialised stores' },
  {
    code: '47760',
    name: 'Retail sale of flowers, plants, seeds, fertilisers, pet animals and pet food in specialised stores',
  },
  { code: '47770', name: 'Retail sale of watches and jewellery in specialised stores' },
  { code: '47781', name: 'Retail sale of antiques and paintings' },
  { code: '47789', name: 'Retail sale in other specialised stores n.e.c.' },
  { code: '47791', name: 'Retail sale of second-hand goods' },
  {
    code: '47810',
    name: 'Retail sale via stalls and markets of food, beverages and tobacco products',
  },
  { code: '47820', name: 'Retail sale via stalls and markets of textiles, clothing and footwear' },
  { code: '47890', name: 'Retail sale via stalls and markets of other goods' },
  { code: '47910', name: 'Retail sale via mail order houses or via Internet' },
  { code: '47990', name: 'Other retail sale not in stores, stalls or markets' },

  // ── Section H: Transportation and Storage ─────────────────────────────────
  { code: '49100', name: 'Passenger rail transport, interurban' },
  { code: '49200', name: 'Freight rail transport' },
  { code: '49311', name: 'Urban and suburban passenger land transport (MRT, LRT, Bus)' },
  { code: '49319', name: 'Other urban and suburban passenger land transport' },
  { code: '49320', name: 'Taxi operation' },
  { code: '49390', name: 'Other passenger land transport n.e.c.' },
  { code: '49410', name: 'Freight transport by road' },
  { code: '49420', name: 'Removal services' },
  { code: '49500', name: 'Transport via pipeline' },
  { code: '50101', name: 'Sea and coastal scheduled passenger water transport' },
  { code: '50102', name: 'Sea and coastal non-scheduled passenger water transport' },
  { code: '50200', name: 'Sea and coastal freight water transport' },
  { code: '50300', name: 'Inland passenger water transport' },
  { code: '50400', name: 'Inland freight water transport' },
  { code: '51100', name: 'Passenger air transport' },
  { code: '51200', name: 'Freight air transport' },
  { code: '52101', name: 'Container terminal activities' },
  { code: '52102', name: 'Port activities' },
  { code: '52103', name: 'Other cargo handling' },
  { code: '52211', name: 'Car parks and parking facilities' },
  { code: '52219', name: 'Other service activities incidental to land transportation' },
  { code: '52220', name: 'Service activities incidental to water transportation' },
  { code: '52230', name: 'Service activities incidental to air transportation' },
  { code: '52240', name: 'Cargo handling' },
  { code: '52290', name: 'Other transportation support activities' },
  { code: '53100', name: 'Postal activities' },
  { code: '53200', name: 'Courier activities' },

  // ── Section I: Accommodation and Food Service ──────────────────────────────
  { code: '55101', name: 'Hotels and resorts' },
  { code: '55102', name: 'Serviced apartments' },
  { code: '55109', name: 'Other short stay accommodation' },
  { code: '55200', name: 'Holiday and other short-stay accommodation' },
  { code: '55300', name: 'Camping grounds, recreational vehicle parks and trailer parks' },
  { code: '55900', name: 'Other accommodation' },
  { code: '56101', name: 'Restaurants' },
  { code: '56102', name: 'Fast food outlets' },
  { code: '56103', name: 'Food courts' },
  { code: '56104', name: 'Catering services' },
  { code: '56109', name: 'Other food service activities' },
  { code: '56210', name: 'Event catering activities' },
  { code: '56290', name: 'Other food service activities' },
  { code: '56301', name: 'Bars and coffee houses' },
  { code: '56302', name: 'Nightclubs and entertainment clubs' },
  { code: '56309', name: 'Other beverage serving activities' },

  // ── Section J: Information and Communications ──────────────────────────────
  { code: '58110', name: 'Book publishing' },
  { code: '58120', name: 'Publishing of directories and mailing lists' },
  { code: '58130', name: 'Publishing of newspapers' },
  { code: '58141', name: 'Publishing of magazines and periodicals' },
  { code: '58142', name: 'Publishing of trade journals' },
  { code: '58190', name: 'Other publishing activities' },
  { code: '58200', name: 'Software publishing' },
  { code: '59110', name: 'Motion picture, video and television programme production activities' },
  {
    code: '59120',
    name: 'Motion picture, video and television programme post-production activities',
  },
  { code: '59130', name: 'Motion picture, video and television programme distribution activities' },
  { code: '59140', name: 'Motion picture projection activities' },
  { code: '59200', name: 'Sound recording and music publishing activities' },
  { code: '60100', name: 'Radio broadcasting' },
  { code: '60200', name: 'Television programming and broadcasting activities' },
  { code: '61100', name: 'Wired telecommunications activities' },
  { code: '61200', name: 'Wireless telecommunications activities' },
  { code: '61300', name: 'Satellite telecommunications activities' },
  { code: '61900', name: 'Other telecommunications activities' },
  { code: '62010', name: 'Computer programming activities' },
  { code: '62020', name: 'Computer consultancy and computer facilities management activities' },
  { code: '62090', name: 'Other information technology and computer service activities' },
  { code: '63110', name: 'Data processing, hosting and related activities' },
  { code: '63120', name: 'Web portals' },
  { code: '63910', name: 'News agency activities' },
  { code: '63990', name: 'Other information service activities n.e.c.' },

  // ── Section K: Financial and Insurance Activities ─────────────────────────
  { code: '64110', name: 'Central banking' },
  { code: '64191', name: 'Commercial banks' },
  { code: '64192', name: 'Finance companies' },
  { code: '64193', name: 'Merchant banks' },
  { code: '64199', name: 'Other monetary intermediation' },
  { code: '64201', name: 'Financial holding companies' },
  { code: '64202', name: 'Non-financial holding companies' },
  { code: '64301', name: 'Investment funds' },
  { code: '64302', name: 'Unit trusts' },
  { code: '64309', name: 'Other collective investment vehicles' },
  { code: '64910', name: 'Financial leasing' },
  { code: '64920', name: 'Other credit granting' },
  { code: '64991', name: 'Investment dealing' },
  { code: '64992', name: 'Money changing and remittance' },
  { code: '64999', name: 'Other financial service activities n.e.c.' },
  { code: '65110', name: 'Life insurance' },
  { code: '65120', name: 'Non-life insurance' },
  { code: '65200', name: 'Reinsurance' },
  { code: '65300', name: 'Pension funding' },
  { code: '66110', name: 'Administration of financial markets' },
  { code: '66120', name: 'Security and commodity contracts dealing activities' },
  {
    code: '66190',
    name: 'Other activities auxiliary to financial services, except insurance and pension funding',
  },
  { code: '66210', name: 'Risk and damage evaluation' },
  { code: '66220', name: 'Activities of insurance agents and brokers' },
  { code: '66290', name: 'Other activities auxiliary to insurance and pension funding' },
  { code: '66300', name: 'Fund management activities' },

  // ── Section L: Real Estate Activities ─────────────────────────────────────
  { code: '68100', name: 'Buying and selling of own real estate' },
  { code: '68201', name: 'Rental and operating of self-owned or leased residential real estate' },
  {
    code: '68202',
    name: 'Rental and operating of self-owned or leased non-residential real estate',
  },
  { code: '68310', name: 'Real estate agencies and brokers' },
  { code: '68320', name: 'Management of real estate on a fee or contract basis' },

  // ── Section M: Professional, Scientific and Technical Activities ───────────
  { code: '69100', name: 'Legal activities' },
  { code: '69200', name: 'Accounting, bookkeeping and auditing activities; tax consultancy' },
  { code: '70100', name: 'Activities of head offices' },
  { code: '70200', name: 'Management consultancy activities' },
  { code: '71110', name: 'Architectural activities' },
  { code: '71120', name: 'Engineering activities and related technical consultancy' },
  { code: '71200', name: 'Technical testing and analysis' },
  {
    code: '72100',
    name: 'Research and experimental development on natural sciences and engineering',
  },
  {
    code: '72200',
    name: 'Research and experimental development on social sciences and humanities',
  },
  { code: '73110', name: 'Advertising agencies' },
  { code: '73120', name: 'Media representation' },
  { code: '73200', name: 'Market research and public opinion polling' },
  { code: '74100', name: 'Specialised design activities' },
  { code: '74200', name: 'Photographic activities' },
  { code: '74300', name: 'Translation and interpretation activities' },
  { code: '74900', name: 'Other professional, scientific and technical activities n.e.c.' },
  { code: '75000', name: 'Veterinary activities' },

  // ── Section N: Administrative and Support Service Activities ──────────────
  { code: '77110', name: 'Renting and leasing of cars and light motor vehicles' },
  { code: '77120', name: 'Renting and leasing of trucks' },
  { code: '77210', name: 'Renting and leasing of recreational and sports goods' },
  { code: '77220', name: 'Renting of video tapes and disks' },
  { code: '77290', name: 'Renting and leasing of other personal and household goods' },
  { code: '77310', name: 'Renting and leasing of agricultural machinery and equipment' },
  {
    code: '77320',
    name: 'Renting and leasing of construction and civil engineering machinery and equipment',
  },
  {
    code: '77330',
    name: 'Renting and leasing of office machinery and equipment (including computers)',
  },
  { code: '77340', name: 'Renting and leasing of water transport equipment' },
  { code: '77350', name: 'Renting and leasing of air transport equipment' },
  {
    code: '77390',
    name: 'Renting and leasing of other machinery, equipment and tangible goods n.e.c.',
  },
  {
    code: '77400',
    name: 'Leasing of intellectual property and similar products, except copyrighted works',
  },
  { code: '78100', name: 'Activities of employment placement agencies' },
  { code: '78200', name: 'Temporary employment agency activities' },
  { code: '78300', name: 'Human resources provision and management of human resources functions' },
  { code: '79110', name: 'Travel agency activities' },
  { code: '79120', name: 'Tour operator activities' },
  { code: '79900', name: 'Other reservation service and related activities' },
  { code: '80100', name: 'Private security activities' },
  { code: '80200', name: 'Security systems service activities' },
  { code: '80300', name: 'Investigation activities' },
  { code: '81100', name: 'Combined facilities support activities' },
  { code: '81210', name: 'General cleaning of buildings' },
  { code: '81220', name: 'Other building and industrial cleaning activities' },
  { code: '81290', name: 'Other cleaning activities' },
  { code: '81300', name: 'Landscape service activities' },
  { code: '82110', name: 'Combined office administrative service activities' },
  {
    code: '82190',
    name: 'Photocopying, document preparation and other specialised office support activities',
  },
  { code: '82200', name: 'Activities of call centres' },
  { code: '82300', name: 'Organisation of conventions and trade shows' },
  { code: '82910', name: 'Activities of collection agencies and credit bureaus' },
  { code: '82920', name: 'Packaging activities' },
  { code: '82990', name: 'Other business support service activities n.e.c.' },

  // ── Section O: Public Administration and Defence ───────────────────────────
  { code: '84110', name: 'General public administration activities' },
  {
    code: '84120',
    name: 'Regulation of the activities of providing health care, education, cultural services and other social services',
  },
  {
    code: '84130',
    name: 'Regulation of and contribution to more efficient operation of businesses',
  },
  { code: '84210', name: 'Foreign affairs' },
  { code: '84220', name: 'Defence activities' },
  { code: '84230', name: 'Justice and judicial activities' },
  { code: '84240', name: 'Public order and safety activities' },
  { code: '84250', name: 'Fire service activities' },
  { code: '84300', name: 'Compulsory social security activities' },

  // ── Section P: Education ───────────────────────────────────────────────────
  { code: '85100', name: 'Pre-primary education' },
  { code: '85200', name: 'Primary education' },
  { code: '85310', name: 'General secondary education' },
  { code: '85320', name: 'Technical and vocational secondary education' },
  { code: '85410', name: 'Post-secondary non-tertiary education' },
  { code: '85421', name: 'Polytechnic education' },
  { code: '85422', name: 'University education' },
  { code: '85423', name: 'Institute for Technical Education (ITE)' },
  { code: '85490', name: 'Other higher education' },
  { code: '85510', name: 'Sports and recreation education' },
  { code: '85520', name: 'Cultural education' },
  { code: '85530', name: 'Driving school activities' },
  { code: '85590', name: 'Other education n.e.c.' },
  { code: '85600', name: 'Educational support activities' },

  // ── Section Q: Human Health and Social Work Activities ────────────────────
  { code: '86101', name: 'Government hospitals' },
  { code: '86102', name: 'Private hospitals' },
  { code: '86103', name: 'Community hospitals' },
  { code: '86200', name: 'Medical and dental practice activities' },
  { code: '86901', name: 'Ambulance service activities' },
  { code: '86902', name: 'Nursing care activities' },
  { code: '86909', name: 'Other human health activities' },
  { code: '87100', name: 'Residential nursing care facilities' },
  {
    code: '87200',
    name: 'Residential care activities for mental retardation, mental health and substance abuse',
  },
  { code: '87300', name: 'Residential care activities for the elderly and disabled' },
  { code: '87900', name: 'Other residential care activities' },
  {
    code: '88100',
    name: 'Social work activities without accommodation for the elderly and disabled',
  },
  { code: '88910', name: 'Child day-care activities' },
  { code: '88990', name: 'Other social work activities without accommodation n.e.c.' },

  // ── Section R: Arts, Entertainment and Recreation ─────────────────────────
  { code: '90000', name: 'Creative, arts and entertainment activities' },
  { code: '91010', name: 'Library and archives activities' },
  { code: '91020', name: 'Museums activities' },
  {
    code: '91030',
    name: 'Operation of historical sites and buildings and similar visitor attractions',
  },
  { code: '91040', name: 'Botanical and zoological gardens and nature reserves activities' },
  { code: '92000', name: 'Gambling and betting activities' },
  { code: '93110', name: 'Operation of sports facilities' },
  { code: '93120', name: 'Activities of sport clubs' },
  { code: '93130', name: 'Fitness facilities' },
  { code: '93190', name: 'Other sports activities' },
  { code: '93210', name: 'Activities of amusement parks and theme parks' },
  { code: '93290', name: 'Other amusement and recreation activities' },

  // ── Section S: Other Service Activities ───────────────────────────────────
  { code: '94110', name: 'Activities of business and employers membership organisations' },
  { code: '94120', name: 'Activities of professional membership organisations' },
  { code: '94200', name: 'Activities of trade unions' },
  { code: '94910', name: 'Activities of religious organisations' },
  { code: '94920', name: 'Activities of political organisations' },
  { code: '94990', name: 'Activities of other membership organisations n.e.c.' },
  { code: '95110', name: 'Repair of computers and peripheral equipment' },
  { code: '95120', name: 'Repair of communication equipment' },
  { code: '95210', name: 'Repair of consumer electronics' },
  { code: '95220', name: 'Repair of household appliances and home and garden equipment' },
  { code: '95230', name: 'Repair of footwear and leather goods' },
  { code: '95240', name: 'Repair of furniture and home furnishings' },
  { code: '95250', name: 'Repair of watches, clocks and jewellery' },
  { code: '95290', name: 'Repair of other personal and household goods' },
  { code: '96010', name: 'Washing and (dry-)cleaning of textile and fur products' },
  { code: '96020', name: 'Hairdressing and other beauty treatment' },
  { code: '96030', name: 'Funeral and related activities' },
  { code: '96040', name: 'Physical well-being activities' },
  { code: '96090', name: 'Other personal service activities n.e.c.' },

  // ── Section T: Activities of Households as Employers ─────────────────────
  { code: '97000', name: 'Activities of households as employers of domestic personnel' },
  {
    code: '98100',
    name: 'Undifferentiated goods-producing activities of private households for own use',
  },
  {
    code: '98200',
    name: 'Undifferentiated service-producing activities of private households for own use',
  },

  // ── Section U: Activities of Extraterritorial Organisations ──────────────
  { code: '99000', name: 'Activities of extraterritorial organisations and bodies' },
];

// ── Seed functions ─────────────────────────────────────────────────────────────

export async function seedCountries(prisma: PrismaClient): Promise<void> {
  const result = await prisma.country.createMany({
    data: COUNTRIES.map((c) => ({
      code: c.code,
      name: c.name,
      uenPattern: c.uenPattern ?? null,
    })),
    skipDuplicates: true,
  });
  // biome-ignore lint/suspicious/noConsoleLog: intentional seed output
  console.log(`[seed] countries: ${result.count} upserted (${COUNTRIES.length} total)`);
}

export async function seedCurrencies(prisma: PrismaClient): Promise<void> {
  const result = await prisma.currency.createMany({
    data: CURRENCIES,
    skipDuplicates: true,
  });
  // biome-ignore lint/suspicious/noConsoleLog: intentional seed output
  console.log(`[seed] currencies: ${result.count} upserted`);
}

export async function seedIndustries(prisma: PrismaClient): Promise<void> {
  const result = await prisma.industry.createMany({
    data: INDUSTRIES.map((i) => ({
      code: i.code,
      name: i.name,
      parentCode: i.parentCode ?? null,
    })),
    skipDuplicates: true,
  });
  // biome-ignore lint/suspicious/noConsoleLog: intentional seed output
  console.log(
    `[seed] industries: ${result.count} upserted (${INDUSTRIES.length} SSIC 2020 subclasses)`,
  );
}
